config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :portfolios
  resources :services
  resources :about_us
  resources :contacts
  resources :blogs
  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/about_us/index.html.slim
section#about-us
  .container
    .center.wow.fadeInDown
      h2 About Corlate
      p.lead
        | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
        br/
        | et dolore magna aliqua. Ut enim ad minim veniam
    /! about us slider
    #about-slider
      #carousel-slider.carousel.slide data-ride="carousel"
        /! Indicators
        ol.carousel-indicators.visible-xs
          li.active data-slide-to="0" data-target="#carousel-slider"
          li data-slide-to="1" data-target="#carousel-slider"
          li data-slide-to="2" data-target="#carousel-slider"
        .carousel-inner
          .item.active
            img.img-responsive alt="" src="assets/slider_one.jpg" /
          .item
            img.img-responsive alt="" src="assets/slider_one.jpg" /
          .item
            img.img-responsive alt="" src="assets/slider_one.jpg" /
        a.left.carousel-control.hidden-xs data-slide="prev" href="#carousel-slider"
          i.fa.fa-angle-left
        a.right.carousel-control.hidden-xs data-slide="next" href="#carousel-slider"
          i.fa.fa-angle-right
      /! /#carousel-slider
    /! /#about-slider
    /! Our Skill
    .skill-wrap.clearfix
      .center.wow.fadeInDown
        h2 Our Skill
        p.lead
          | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
          br/
          | et dolore magna aliqua. Ut enim ad minim veniam
      .row
        .col-sm-3
          .sinlge-skill.wow.fadeInDown data-wow-delay="300ms" data-wow-duration="1000ms"
            .joomla-skill
              p
                em 85%
              p Joomla
        .col-sm-3
          .sinlge-skill.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
            .html-skill
              p
                em 95%
              p HTML
        .col-sm-3
          .sinlge-skill.wow.fadeInDown data-wow-delay="900ms" data-wow-duration="1000ms"
            .css-skill
              p
                em 80%
              p CSS
        .col-sm-3
          .sinlge-skill.wow.fadeInDown data-wow-delay="1200ms" data-wow-duration="1000ms"
            .wp-skill
              p
                em 90%
              p Wordpress
    /! /.our-skill
    /! our-team
    .team
      .center.wow.fadeInDown
        h2 Team of Corlate
        p.lead
          | Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
          br/
          | et dolore magna aliqua. Ut enim ad minim veniam
      .row.clearfix
        .col-md-4.col-sm-6
          .single-profile-top.wow.fadeInDown data-wow-delay="300ms" data-wow-duration="1000ms"
            .media
              .pull-left
                a href="#"
                  img.media-object alt="" src="assets/man1.jpg" /
              .media-body
                h4 Jhon Doe
                h5 Founder and CEO
                ul.tag.clearfix
                  li.btn
                    a href="#"  Web
                  li.btn
                    a href="#"  Ui
                  li.btn
                    a href="#"  Ux
                  li.btn
                    a href="#"  Photoshop
                ul.social_icons
                  li
                    a href="#"
                      i.fa.fa-facebook
                  li
                    a href="#"
                      i.fa.fa-twitter
                  li
                    a href="#"
                      i.fa.fa-google-plus
            /! /.media
            p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
        /! /.col-lg-4
        .col-md-4.col-sm-6.col-md-offset-2
          .single-profile-top.wow.fadeInDown data-wow-delay="300ms" data-wow-duration="1000ms"
            .media
              .pull-left
                a href="#"
                  img.media-object alt="" src="assets/man2.jpg" /
              .media-body
                h4 Jhon Doe
                h5 Founder and CEO
                ul.tag.clearfix
                  li.btn
                    a href="#"  Web
                  li.btn
                    a href="#"  Ui
                  li.btn
                    a href="#"  Ux
                  li.btn
                    a href="#"  Photoshop
                ul.social_icons
                  li
                    a href="#"
                      i.fa.fa-facebook
                  li
                    a href="#"
                      i.fa.fa-twitter
                  li
                    a href="#"
                      i.fa.fa-google-plus
            /! /.media
            p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
        /! /.col-lg-4
      /! /.row
      .row.team-bar
        .first-one-arrow.hidden-xs
          hr/
        .first-arrow.hidden-xs
          hr/
          i.fa.fa-angle-up
        .second-arrow.hidden-xs
          hr/
          i.fa.fa-angle-down
        .third-arrow.hidden-xs
          hr/
          i.fa.fa-angle-up
        .fourth-arrow.hidden-xs
          hr/
          i.fa.fa-angle-down
      /! skill_border
      .row.clearfix
        .col-md-4.col-sm-6.col-md-offset-2
          .single-profile-bottom.wow.fadeInUp data-wow-delay="600ms" data-wow-duration="1000ms"
            .media
              .pull-left
                a href="#"
                  img.media-object alt="" src="assets/man3.jpg" /
              .media-body
                h4 Jhon Doe
                h5 Founder and CEO
                ul.tag.clearfix
                  li.btn
                    a href="#"  Web
                  li.btn
                    a href="#"  Ui
                  li.btn
                    a href="#"  Ux
                  li.btn
                    a href="#"  Photoshop
                ul.social_icons
                  li
                    a href="#"
                      i.fa.fa-facebook
                  li
                    a href="#"
                      i.fa.fa-twitter
                  li
                    a href="#"
                      i.fa.fa-google-plus
            /! /.media
            p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
        .col-md-4.col-sm-6.col-md-offset-2
          .single-profile-bottom.wow.fadeInUp data-wow-delay="600ms" data-wow-duration="1000ms"
            .media
              .pull-left
                a href="#"
                  img.media-object alt="" src="assets/man4.jpg" /
              .media-body
                h4 Jhon Doe
                h5 Founder and CEO
                ul.tag.clearfix
                  li.btn
                    a href="#"  Web
                  li.btn
                    a href="#"  Ui
                  li.btn
                    a href="#"  Ux
                  li.btn
                    a href="#"  Photoshop
                ul.social_icons
                  li
                    a href="#"
                      i.fa.fa-facebook
                  li
                    a href="#"
                      i.fa.fa-twitter
                  li
                    a href="#"
                      i.fa.fa-google-plus
            /! /.media
            p There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
      /! /.row
    /! section
  /! /.container
/! /about-us
section#bottom
  .container.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
    .row
      .col-md-3.col-sm-6
        .widget
          h3 Company
          ul
            li
              a href="#"  About us
            li
              a href="#"  We are hiring
            li
              a href="#"  Meet the team
            li
              a href="#"  Copyright
            li
              a href="#"  Terms of use
            li
              a href="#"  Privacy policy
            li
              a href="#"  Contact us
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Support
          ul
            li
              a href="#"  Faq
            li
              a href="#"  Blog
            li
              a href="#"  Forum
            li
              a href="#"  Documentation
            li
              a href="#"  Refund policy
            li
              a href="#"  Ticket system
            li
              a href="#"  Billing system
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Developers
          ul
            li
              a href="#"  Web Development
            li
              a href="#"  SEO Marketing
            li
              a href="#"  Theme
            li
              a href="#"  Development
            li
              a href="#"  Email Marketing
            li
              a href="#"  Plugin Development
            li
              a href="#"  Article Writing
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Our Partners
          ul
            li
              a href="#"  Adipisicing Elit
            li
              a href="#"  Eiusmod
            li
              a href="#"  Tempor
            li
              a href="#"  Veniam
            li
              a href="#"  Exercitation
            li
              a href="#"  Ullamco
            li
              a href="#"  Laboris
      /! /.col-md-3

app/views/blogs/index.html.slim
section#blog.container
  .center
    h2 Blogs
    p.lead Pellentesque habitant morbi tristique senectus et netus et malesuada
  .blog
    .row
      .col-md-8
        .blog-item
          .row
            .col-xs-12.col-sm-2.text-center
              .entry-meta
                span#publish_date 07  NOV
                span
                  i.fa.fa-user
                  a href="#"  John Doe
                span
                  i.fa.fa-comment
                  a href="blog-item.html#comments"  2 Comments
                span
                  i.fa.fa-heart
                  a href="#"  56 Likes
            .col-xs-12.col-sm-10.blog-content
              a href="#"
                img.img-responsive.img-blog alt="" src="assets/blog/blog1.jpg" width="100%" /
              h2
                a href="blog-item.html"  Consequat bibendum quam liquam viverra
              h3 Curabitur quis libero leo, pharetra mattis eros. Praesent consequat libero eget dolor convallis vel rhoncus magna scelerisque. Donec nisl ante, elementum eget posuere a, consectetur a metus. Proin a adipiscing sapien. Suspendisse vehicula porta lectus vel semper. Nullam sapien elit, lacinia eu tristique non.posuere at mi. Morbi at turpis id urna ullamcorper ullamcorper.
              a.btn.btn-primary.readmore href="blog-item.html"
                | Read More
                i.fa.fa-angle-right
        /! /.blog-item
        .blog-item
          .row
            .col-sm-2.text-center
              .entry-meta
                span#publish_date 07  NOV
                span
                  i.fa.fa-user
                  a href="#"  John Doe
                span
                  i.fa.fa-comment
                  a href="blog-item.html#comments"  2 Comments
                span
                  i.fa.fa-heart
                  a href="#"  56 Likes
            .col-sm-10.blog-content
              a href=""
                img.img-responsive.img-blog alt="" src="assets/blog/blog2.jpg" width="100%" /
              h2
                a href="blog-item.html"  Consequat bibendum quam liquam viverra
              h3 Curabitur quis libero leo, pharetra mattis eros. Praesent consequat libero eget dolor convallis vel rhoncus magna scelerisque. Donec nisl ante, elementum eget posuere a, consectetur a metus. Proin a adipiscing sapien. Suspendisse vehicula porta lectus vel semper. Nullam sapien elit, lacinia eu tristique non.posuere at mi. Morbi at turpis id urna ullamcorper ullamcorper.
              a.btn.btn-primary.readmore href="blog-item.html"
                | Read More
                i.fa.fa-angle-right
        /! /.blog-item
        ul.pagination.pagination-lg
          li
            a href="#"
              i.fa.fa-long-arrow-left
              | Previous Page
          li.active
            a href="#"  1
          li
            a href="#"  2
          li
            a href="#"  3
          li
            a href="#"  4
          li
            a href="#"  5
          li
            a href="#"
              | Next Page
              i.fa.fa-long-arrow-right
        /! /.pagination
      /! /.col-md-8
      aside.col-md-4
        .widget.search
          form role="form"
            input.form-control.search_box autocomplete="off" placeholder=("Search Here") type="text" /
        /! /.search
        .widget.categories
          h3 Recent Comments
          .row
            .col-sm-12
              .single_comments
                img alt="" src="assets/blog/avatar3.png" /
                p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                .entry-meta.small.muted
                  span
                    | By
                    / = succeed "</span" do
                    /   a href="#"  Alex
                    span
                      | On
                      a href="#"  Creative
              .single_comments
                img alt="" src="assets/blog/avatar3.png" /
                p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                .entry-meta.small.muted
                  span
                    | By
                    / = succeed "</span" do
                    /   a href="#"  Alex
                    span
                      | On
                      a href="#"  Creative
              .single_comments
                img alt="" src="assets/blog/avatar3.png" /
                p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                .entry-meta.small.muted
                  span
                    | By
                    / = succeed "</span" do
                    /   a href="#"  Alex
                    span
                      | On
                      a href="#"  Creative
        /! /.recent comments
        .widget.categories
          h3 Categories
          .row
            .col-sm-6
              ul.blog_category
                li
                  a href="#"
                    | Computers
                    span.badge 04
                li
                  a href="#"
                    | Smartphone
                    span.badge 10
                li
                  a href="#"
                    | Gedgets
                    span.badge 06
                li
                  a href="#"
                    | Technology
                    span.badge 25
        /! /.categories
        .widget.archieve
          h3 Archieve
          .row
            .col-sm-12
              ul.blog_archieve
                li
                  a href="#"
                    i.fa.fa-angle-double-right
                    | December 2013
                    span.pull-right (97)
                li
                  a href="#"
                    i.fa.fa-angle-double-right
                    | November 2013
                    span.pull-right (32)
                li
                  a href="#"
                    i.fa.fa-angle-double-right
                    | October 2013
                    span.pull-right (19)
                li
                  a href="#"
                    i.fa.fa-angle-double-right
                    | September 2013
                    span.pull-right (08)
        /! /.archieve
        .widget.tags
          h3 Tag Cloud
          ul.tag-cloud
            li
              a.btn.btn-xs.btn-primary href="#"  Apple
            li
              a.btn.btn-xs.btn-primary href="#"  Barcelona
            li
              a.btn.btn-xs.btn-primary href="#"  Office
            li
              a.btn.btn-xs.btn-primary href="#"  Ipod
            li
              a.btn.btn-xs.btn-primary href="#"  Stock
            li
              a.btn.btn-xs.btn-primary href="#"  Race
            li
              a.btn.btn-xs.btn-primary href="#"  London
            li
              a.btn.btn-xs.btn-primary href="#"  Football
            li
              a.btn.btn-xs.btn-primary href="#"  Porche
            li
              a.btn.btn-xs.btn-primary href="#"  Gadgets
        /! /.tags
        .widget.blog_gallery
          h3 Our Gallery
          ul.sidebar-gallery
            li
              a href="#"
                img alt="" src="assets/blog/gallery1.png" /
            li
              a href="#"
                img alt="" src="assets/blog/gallery2.png" /
            li
              a href="#"
                img alt="" src="assets/blog/gallery3.png" /
            li
              a href="#"
                img alt="" src="assets/blog/gallery4.png" /
            li
              a href="#"
                img alt="" src="assets/blog/gallery5.png" /
            li
              a href="#"
                img alt="" src="assets/blog/gallery6.png" /
        /! /.blog_gallery
    /! /.row
/! /#blog
section#bottom
  .container.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
    .row
      .col-md-3.col-sm-6
        .widget
          h3 Company
          ul
            li
              a href="#"  About us
            li
              a href="#"  We are hiring
            li
              a href="#"  Meet the team
            li
              a href="#"  Copyright
            li
              a href="#"  Terms of use
            li
              a href="#"  Privacy policy
            li
              a href="#"  Contact us
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Support
          ul
            li
              a href="#"  Faq
            li
              a href="#"  Blog
            li
              a href="#"  Forum
            li
              a href="#"  Documentation
            li
              a href="#"  Refund policy
            li
              a href="#"  Ticket system
            li
              a href="#"  Billing system
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Developers
          ul
            li
              a href="#"  Web Development
            li
              a href="#"  SEO Marketing
            li
              a href="#"  Theme
            li
              a href="#"  Development
            li
              a href="#"  Email Marketing
            li
              a href="#"  Plugin Development
            li
              a href="#"  Article Writing
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Our Partners
          ul
            li
              a href="#"  Adipisicing Elit
            li
              a href="#"  Eiusmod
            li
              a href="#"  Tempor
            li
              a href="#"  Veniam
            li
              a href="#"  Exercitation
            li
              a href="#"  Ullamco
            li
              a href="#"  Laboris
      /! /.col-md-3

app/views/contacts/index.html.slim
section#contact-info
  .center
    h2 How to Reach Us?
    p.lead Lorem ipsum dolor sit amet, consectetur adipisicing elit
  .gmap-area
    .container
      .row
        .col-sm-5.text-center
          .gmap
            iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=JoomShaper,+Dhaka,+Dhaka+Division,+Bangladesh&amp;aq=0&amp;oq=joomshaper&amp;sll=37.0625,-95.677068&amp;sspn=42.766543,80.332031&amp;ie=UTF8&amp;hq=JoomShaper,&amp;hnear=Dhaka,+Dhaka+Division,+Bangladesh&amp;ll=23.73854,90.385504&amp;spn=0.001515,0.002452&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=1073661719450182870&amp;output=embed"
        .col-sm-7.map-content
          ul.row
            li.col-sm-6
              address
              h5 Head Office
              p
                | 1537 Flint Street
                br/
                | Tumon, MP 96911
              p
                | Phone:670-898-2847
                br/
                | Email Address:info@domain.com
              address
              h5 Zonal Office
              p
                | 1537 Flint Street
                br/
                | Tumon, MP 96911
              p
                | Phone:670-898-2847
                br/
                | Email Address:info@domain.com
            li.col-sm-6
              address
              h5 Zone#2 Office
              p
                | 1537 Flint Street
                br/
                | Tumon, MP 96911
              p
                | Phone:670-898-2847
                br/
                | Email Address:info@domain.com
              address
              h5 Zone#3 Office
              p
                | 1537 Flint Street
                br/
                | Tumon, MP 96911
              p
                | Phone:670-898-2847
                br/
                | Email Address:info@domain.com
/! /gmap_area
section#contact-page
  .container
    .center
      h2 Drop Your Message
      p.lead Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    .row.contact-wrap
      .status.alert.alert-success style=("display: none")
      form#main-contact-form.contact-form action="sendemail.php" method="post" name="contact-form"
        .col-sm-5.col-sm-offset-1
          .form-group
            label Name *
            input.form-control name="name" required="required" type="text" /
          .form-group
            label Email *
            input.form-control name="email" required="required" type="email" /
          .form-group
            label Phone
            input.form-control type="number" /
          .form-group
            label Company Name
            input.form-control type="text" /
        .col-sm-5
          .form-group
            label Subject *
            input.form-control name="subject" required="required" type="text" /
          .form-group
            label Message *
            textarea#message.form-control name="message" required="required" rows="8"
          .form-group
            button.btn.btn-primary.btn-lg name="submit" required="required" type="submit"  Submit Message
    /! /.row
  /! /.container
/! /#contact-page
section#bottom
  .container.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
    .row
      .col-md-3.col-sm-6
        .widget
          h3 Company
          ul
            li
              a href="#"  About us
            li
              a href="#"  We are hiring
            li
              a href="#"  Meet the team
            li
              a href="#"  Copyright
            li
              a href="#"  Terms of use
            li
              a href="#"  Privacy policy
            li
              a href="#"  Contact us
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Support
          ul
            li
              a href="#"  Faq
            li
              a href="#"  Blog
            li
              a href="#"  Forum
            li
              a href="#"  Documentation
            li
              a href="#"  Refund policy
            li
              a href="#"  Ticket system
            li
              a href="#"  Billing system
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Developers
          ul
            li
              a href="#"  Web Development
            li
              a href="#"  SEO Marketing
            li
              a href="#"  Theme
            li
              a href="#"  Development
            li
              a href="#"  Email Marketing
            li
              a href="#"  Plugin Development
            li
              a href="#"  Article Writing
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Our Partners
          ul
            li
              a href="#"  Adipisicing Elit
            li
              a href="#"  Eiusmod
            li
              a href="#"  Tempor
            li
              a href="#"  Veniam
            li
              a href="#"  Exercitation
            li
              a href="#"  Ullamco
            li
              a href="#"  Laboris
      /! /.col-md-3

app/views/home/_bottom.html.slim
section#bottom
  .container.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
    .row
      .col-md-3.col-sm-6
        .widget
          h3 Company
          ul
            li
              a href="#"  About us
            li
              a href="#"  We are hiring
            li
              a href="#"  Meet the team
            li
              a href="#"  Copyright
            li
              a href="#"  Terms of use
            li
              a href="#"  Privacy policy
            li
              a href="#"  Contact us
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Support
          ul
            li
              a href="#"  Faq
            li
              a href="#"  Blog
            li
              a href="#"  Forum
            li
              a href="#"  Documentation
            li
              a href="#"  Refund policy
            li
              a href="#"  Ticket system
            li
              a href="#"  Billing system
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Developers
          ul
            li
              a href="#"  Web Development
            li
              a href="#"  SEO Marketing
            li
              a href="#"  Theme
            li
              a href="#"  Development
            li
              a href="#"  Email Marketing
            li
              a href="#"  Plugin Development
            li
              a href="#"  Article Writing
      /! /.col-md-3
      .col-md-3.col-sm-6
        .widget
          h3 Our Partners
          ul
            li
              a href="#"  Adipisicing Elit
            li
              a href="#"  Eiusmod
            li
              a href="#"  Tempor
            li
              a href="#"  Veniam
            li
              a href="#"  Exercitation
            li
              a href="#"  Ullamco
            li
              a href="#"  Laboris
      /! /.col-md-3
/! /#bottom

app/views/home/_conatcat_info.html.slim
section#conatcat-info
  .container
    .row
      .col-sm-8
        .media.contact-info.wow.fadeInDown data-wow-delay="600ms" data-wow-duration="1000ms"
          .pull-left
            i.fa.fa-phone
          .media-body
            h2 Have a question or need a custom quote?
            p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation +0123 456 70 80
  /! /.container
/! /#conatcat-info

app/views/home/index.html.slim
/slider
= render 'slider'


/feature
= render 'features'


/portfolios
= render 'portfolios'

/services
= render 'services'

/middle
= render 'middle'

/partner
= render 'partner'

/conatcat-info
= render 'conatcat_info'

/bottom
= render 'bottom'

app/views/shared/_header.html.slim
header#header
  .top-bar
    .container
      .row
        .col-sm-6.col-xs-4
          .top-number
            p
              i.fa.fa-phone-square
              | +0123 456 70 90
        .col-sm-6.col-xs-8
          .social
            ul.social-share
              li
                a href="#"
                  i.fa.fa-facebook
              li
                a href="#"
                  i.fa.fa-twitter
              li
                a href="#"
                  i.fa.fa-linkedin
              li
                a href="#"
                  i.fa.fa-dribbble
              li
                a href="#"
                  i.fa.fa-skype
            .search
              form role="form"
                input.search-form autocomplete="off" placeholder="Search" type="text" /
                i.fa.fa-search
    /! /.container
  /! /.top-bar
  nav.navbar.navbar-inverse role="banner"
    .container
      .navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to home_index_path, class: "navbar-brand"
          = image_tag "logo.png", class: "img-responsive"
      .collapse.navbar-collapse.navbar-right
        ul.nav.navbar-nav
          li.active
            = link_to home_index_path
              |Home
          li
            = link_to about_us_path
              |About Us
          li
            = link_to services_path
              |Services
          li
            = link_to portfolios_path
              |Portfolio
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Pages
              i.fa.fa-angle-down
            ul.dropdown-menu
              li
                a href="blog-item.html"  Blog Single
              li
                a href="pricing.html"  Pricing
              li
                a href="404.html"  404
              li
                a href="shortcodes.html"  Shortcodes
          li
            = link_to blogs_path
              |Blog
          li
            = link_to contacts_path
              |Contact
    /! /.container
  /! /nav
/! /header